= Upsilon Project Documentation

[discrete]
== Introduction

image:https://travis-ci.org/upsilonproject/upsilon-docs.svg?branch=master["Build Status", link="https://travis-ci.org/upsilonproject/upsilon-docs"]

These are the Upsilon docs. They are available at
http://docs.upsilonproject.io[docs.upsilonproject.io] and the
https://github.com/upsilonproject/upsilon-docs[upsilon-docs project on GitHub].

To learn more about the Upsilon project, please visit http://www.upsilonproject.io.

[discrete]
=== Help improve this documentation!

This documentation is written in a very simple human-readable language called
link:http://www.methods.co.nz/asciidoc/[AsciiDoc]. This means basically anyone
can make changes and improvements by just visiting the GitHub repository for
the documentation raise a GitHub pull request against your own feature branch.

If you don't know how to do that, please just
link:https://github.com/upsilonproject/upsilon-docs/issues/new[**tell us how to improve
documentation**] by raising an issue ticket against the docs and we'll take it
from there!

== Documentation Structure

This documentation is organized into the following sections:

* xref:services-index.adoc[Services & Introduction] - Overview of Upsilon services and architecture
* xref:deployment-environments-index.adoc[Installation & Deployment] - How to install and deploy Upsilon
* xref:setup-index.adoc[Setup] - Initial setup and configuration
* xref:usage-index.adoc[Usage] - How to use Upsilon
* xref:integration-index.adoc[Integration] - Integration with other tools
* xref:commonissues.adoc[Common Issues] - Troubleshooting guide
* xref:upgrading.adoc[Upgrading] - Upgrade instructions
* xref:appendix.adoc[Appendix] - Additional resources
